project_id = "qitfusqfwdbgcrbuuxiu"

[functions.process-tender]
enabled = true
verify_jwt = false
import_map = "./functions/process-tender/deno.json"
entrypoint = "./functions/process-tender/index.ts"