project_id = "qitfusqfwdbgcrbuuxiu"

[functions.process-tender]
enabled = true
verify_jwt = false
import_map = "./functions/process-tender/deno.json"
entrypoint = "./functions/process-tender/index.ts"

[functions.match-knowledge-assets]
enabled = true
verify_jwt = false
import_map = "./functions/match-knowledge-assets/deno.json"
entrypoint = "./functions/match-knowledge-assets/index.ts"

[functions.process-knowledge-assets]
enabled = true
verify_jwt = false
import_map = "./functions/process-knowledge-assets/deno.json"
entrypoint = "./functions/process-knowledge-assets/index.ts"

[functions.generate-response]
enabled = true
verify_jwt = false
entrypoint = "./functions/generate-response/index.ts"

[functions.export-filled-excel]
enabled = true
verify_jwt = false
import_map = "./functions/export-filled-excel/deno.json"
entrypoint = "./functions/export-filled-excel/index.ts"

[functions.export-response-doc]
enabled = true
verify_jwt = false
import_map = "./functions/export-response-doc/deno.json"
entrypoint = "./functions/export-response-doc/index.ts"